== Suite JSON for execution mode normal
The suite JSONs have different formats depending on the execution mode.

. Example Suite for execution mode normal
[source,json]
----
{
  "name": "suite name",        <1>
  "tags": [],                  <2>
  "steps": {},                 <3>
  "testcases": [],             <4>
  "executionMode": "normal"    <5>
}
----
<1> (Optional) The name for this suite. Defaults to 'unnamed suite'.
<2> (Optional) A list of tags. Could be used for analysis or statistics.
<3> The definition of the steps available for the test cases.
<4> The test cases of this suite.
<5> In this case the value 'normal'.



. Example for a step
[source,json]
----
"steps": {
  "StepId_1": {               <1>
    "class": "normal",        <2>
    "name": "Step 1",         <3>
    "description": "Desc 1"   <4>
}
----
<1> The Id of this step. This id is used to reference  step from the test case.
<2> The name under which this step could be found in the step registry.
<3> (Optional) A name for this step shown in the step execution. Defaults to the 'class' property
<4> (Optional) A decription for this step.

. Example for a test case
[source,json]
----
{
  "testcases": [
    {
      "name": "TC 1",                <1>
      "description": "TC Desc 1",    <2>
      "steps": [                     <3>
        "StepId_1"                   <4>
      ],
      "data": [                      <5>
        "data TC 1 Step 1"           <6>
      ]
    }
  ]
}
----
<1> The name of this test case.
<2> (Optional) a description for this test case.
<3> All the steps to be executed in this test case.
<4> The Id of a step.
<5> For each step there must be one entry in the data property. If no data needed for a step then the value must be 'null'.
<6> The data for the step. This could be an array, string or an object.
