=== Suite
Defines the format of a suite as it is used by the runner.

The suite is build of test cases and steps.
A suite could be executed in two different modes. The 'normal' mode is how the most frameworks
executes tests::

* normal +
The execution starts with the first test case, then for this test case. Then
for this test case one step after the other is executed.

* batch +
This mode has special requirements for the suite definition. Each test case must have the same amount of steps.
This does not mean that all the steps must be executed for each test case, but it must be defined.

.Suite
[source, js]
----
const suite = {
  name: 'test suite 1',   <1>
  tags: [],               <2>
  description: 'Desc 1',  <3>
  testcases: [],          <4>
  steps: {},              <5>
  executionMode: 'batch'  <6>
}
----
<1> The name of this suite

<2> An array of strings. The idea of the tag is that it could be
used to filter for suites later on.

<3> Any description for this suite.
<4> The test cases of this suite. This array contains the references to the test case definition
<5> All the steps of this suite. The steps are stores by there id
<6> Defines the execution mode for executing the suite. The normal mode is the batch mode.
